import time
from gc import set_debug

import torch
from inference.generate import generate
from inference.adaptive_controller import AdaptiveController
from .generate import get_model
from transformers import DynamicCache
import argparse

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    
@torch.no_grad()
def generate_speculative_custom(main_model,
                                draft_model,
                                input_ids,
                                max_new_tokens=512,
                                device=DEVICE,
                                gamma=5,
                                use_cache=False,
                                return_stats=False,
                                **kwargs):
    """
    Speculative generation function which will utilize draft model to speculate gamma tokens, then verify it with main model in one pass
    
    Args:
        main_model: The main model
        draft_model: The draft model
        input_ids: Input sequence of shape: (B, T)
        max_new_tokens: Maximum number of tokens to generate
        device: Device to use for generation
        gamma: Number of tokens to speculate using draft model
        use_cache: Boolean variable to determine whether to use cache or not
        return_stats: Boolean variable to determine whether to return generation stats or not
    """
    
    # If model is using cache, then reset cache before generation
    if use_cache:
        for block in draft_model.blocks:
            block.sa_heads.reset_cache()
        
    # Pass the input ids once to prefill the decoder cache
    speculated_ids = draft_model.generate(
        input_ids,
        max_new_tokens=gamma,
        use_cache=use_cache
    )
    
    tokens_generated = 0
    total_accepted_tokens = 0
    draft_generated_tokens = 0
    total_steps = 0
    while tokens_generated < max_new_tokens:
        input_len = input_ids.shape[1]
        # Take the new tokens speculated by the draft model
        draft_tokens = speculated_ids[:, input_len:]
        
        # Pass the speculated ids to the main model for verification
        target_logits, _ = main_model(speculated_ids, use_cache=False)
        
        # Shift indices by -1 to align the target model's output logits with the draft tokens they are predicting.
        verification_logits = target_logits[:, input_len - 1 : input_len + gamma - 1, :]
        main_tokens = torch.argmax(verification_logits, dim=-1)
        
        # Calculate the total number of accepted tokens
        accepted_tokens = 0
        for i in range(gamma):
            draft_token = draft_tokens[0, i]
            main_token = main_tokens[0, i]
            
            if draft_token == main_token:
                accepted_tokens += 1
            else:
                break
        
        # Take the last correct token predicted by the main model
        correction_token = torch.argmax(target_logits[:, input_len + accepted_tokens - 1, :], dim=-1)
        # Valid draft is all the draft tokens which are accepted by the main model
        valid_draft = draft_tokens[:, :accepted_tokens]
        
        # Concatenate the valid draft and correction token to get the new input ids
        new_tokens = torch.cat([valid_draft, correction_token.unsqueeze(0)], dim=1)
        input_ids = torch.cat([input_ids, new_tokens], dim=1)
        
        # Increment the counters accordingly
        tokens_generated += (accepted_tokens + 1)
        total_accepted_tokens += accepted_tokens
        draft_generated_tokens += gamma
        total_steps += 1
        
        # If the draft model is using cache, rollback the KV Cache to the actual valid length
        if use_cache:
            valid_len = input_len + accepted_tokens
            for block in draft_model.blocks:
                block.sa_heads.truncate_cache(valid_len)
            
            draft_input = correction_token.unsqueeze(0)
        else:
            draft_input = input_ids
        
        # Speculate the next chunk using the draft model
        next_chunk = draft_model.generate(
            draft_input,
            max_new_tokens=gamma,
            use_cache=use_cache
        )
        
        # Generate the next speculated ids
        input_length_passed = draft_input.shape[1]
        newly_generated_gamma = next_chunk[:, input_length_passed:]
        speculated_ids = torch.cat([input_ids, newly_generated_gamma], dim=1)        
    
    # Acceptance rate is the total number of tokens accepted divided by total number of tokens generated by the draft model
    acceptance_rate = total_accepted_tokens / draft_generated_tokens
    # Mean accepted tokens is the average number of tokens accepted in each step
    mean_accepted = total_accepted_tokens / total_steps

    stats = {
        "acceptance_rate": acceptance_rate,
        "mean_accepted": mean_accepted
    }

    if return_stats:
        return input_ids, stats
    else:
        return input_ids          

@torch.no_grad()
def generate_speculative_standard(main_model,
                                  draft_model,
                                  input_ids,
                                  attention_mask,
                                  max_new_tokens=512,
                                  device=DEVICE,
                                  gamma=5,
                                  use_cache=False,
                                  return_stats=False,
                                  profiler=None,
                                  controller=None):
    """
    Speculative generation function which will utilize draft model to speculate gamma tokens, then verify it with main model in one pass

    Args:
        main_model: The main model
        draft_model: The draft model
        input_ids: Input sequence of shape: (B, T)
        attention_mask: Mask for specifying tokens to attend
        max_new_tokens: Maximum number of tokens to generate
        device: Device to use for generation
        gamma: Number of tokens to speculate using draft model
        use_cache: Boolean variable to determine whether to use cache or not
        return_stats: Boolean variable to determine whether to return generation stats or not
        profiler: Profiler for measuring time taken by each operation
        controller: Adaptive controller for speculative decoding
    """
    
    # If model is using cache, then reset cache before generation
    draft_cache = DynamicCache() if use_cache else None
    target_cache = DynamicCache() if use_cache else None

    if controller is not None:
        # Stats tracking
        steps = 0
        config_history = []
        tps_history = []

        current_gamma = controller.current_gamma
        current_cache = controller.current_cache
    else:
        current_gamma = gamma
        current_cache = use_cache

    # Target model initial prefill
    target_out = main_model(input_ids, past_key_values=target_cache, use_cache=current_cache)
    target_cache = target_out.past_key_values if current_cache else None
    first_target_token = torch.argmax(target_out.logits[:, -1, :], dim=-1, keepdim=True)
    
    # Pass the input ids once to prefill the decoder cache
    if profiler: profiler.start_stage("draft_speculation")
    generated = []
    if current_cache:
        outputs = draft_model(input_ids, attention_mask=attention_mask, use_cache=True)
        draft_cache = outputs.past_key_values
        
        logits = outputs.logits[:, -1, :]
        next_token = torch.argmax(logits, dim=-1, keepdim=True)
        generated.append(next_token)
        current_input = next_token
        current_attention_mask = attention_mask.clone()
        
        for _ in range(current_gamma-1):
            current_attention_mask = torch.cat([
                current_attention_mask,
                torch.ones((input_ids.shape[0], 1), device=device)
            ], dim=1)
            position_ids = (current_attention_mask.cumsum(dim=-1) - 1)[:, -1:]
            
            outputs = draft_model(
                current_input,
                attention_mask=current_attention_mask,
                position_ids=position_ids,
                past_key_values=draft_cache,
                use_cache=True
            )
            
            draft_cache = outputs.past_key_values
            logits = outputs.logits[:, -1, :]
            next_token = torch.argmax(logits, dim=-1, keepdim=True)
            
            generated.append(next_token)
            current_input = next_token
    else:
        current_input = input_ids
        
        for _ in range(current_gamma):
            outputs = draft_model(
                current_input,
                use_cache=False
            )
            
            logits = outputs.logits[:, -1, :]
            next_token = torch.argmax(logits, dim=-1, keepdim=True)
            
            if next_token is not None:
                generated.append(next_token)
                current_input = torch.cat((current_input, next_token), dim=1)
    if profiler: profiler.end_stage("draft_speculation")
    
    draft_tokens = torch.cat(generated, dim=1)
    
    speculated_ids = torch.cat([input_ids, draft_tokens], dim=1)
    past_correction_token = None
    
    tokens_generated = 0
    total_accepted_tokens = 0
    draft_generated_tokens = 0
    total_steps = 0
    phase_stats = {}
    while tokens_generated < max_new_tokens:
        chunk_start = time.time()

        input_len = input_ids.shape[1]
        # Take the new tokens speculated by the draft model
        draft_tokens = speculated_ids[:, input_len:]
        actual_gamma = draft_tokens.shape[1]

        if profiler: profiler.start_stage("target_verification")
        # Pass the speculated ids to the main model for verification
        if current_cache:
            if past_correction_token is None:
                target_out = main_model(
                    draft_tokens,
                    past_key_values=target_cache,
                    use_cache=True
                )
                target_cache = target_out.past_key_values
                
                target_preds = torch.cat([
                    first_target_token,
                    torch.argmax(target_out.logits[:, :-1, :], dim=-1)
                ], dim=1)
            else:
                verification_chunk = torch.cat([past_correction_token, draft_tokens], dim=1)
                target_out = main_model(
                    verification_chunk,
                    past_key_values=target_cache,
                    use_cache=True
                )
                target_cache = target_out.past_key_values
                
                target_preds = torch.argmax(target_out.logits[:, :-1, :], dim=-1)
        else:
            target_out = main_model(speculated_ids, use_cache=False)
            target_logits = target_out.logits
            verification_logits = target_logits[:, input_len - 1 : input_len + actual_gamma - 1, :]
            target_preds = torch.argmax(verification_logits, dim=-1)
        if profiler: profiler.end_stage("target_verification")
        
        if profiler: profiler.start_stage("comparison_logic")
        # Calculate the total number of accepted tokens
        accepted_tokens = 0
        for i in range(actual_gamma):
            draft_token = draft_tokens[0, i]
            main_token = target_preds[0, i]
            
            if draft_token == main_token:
                accepted_tokens += 1
            else:
                break
        
        # Take the last correct token predicted by the main model
        if current_cache:
            if past_correction_token is None:
                if accepted_tokens == 0:
                    correction_token = first_target_token
                else:
                    correction_token = torch.argmax(target_out.logits[:, accepted_tokens - 1, :], dim=-1, keepdim=True)
            else:
                # In verification_chunk: index 0 is correction, index 1..gamma are drafts
                # Rejection at accepted_tokens means the correct replacement is at index accepted_tokens
                correction_token = torch.argmax(target_out.logits[:, accepted_tokens, :], dim=-1, keepdim=True)
        else:
            correction_token = torch.argmax(target_logits[:, input_len + accepted_tokens - 1, :], dim=-1, keepdim=True)
        correction_token = correction_token.view(input_ids.shape[0], 1)
        if profiler: profiler.end_stage("comparison_logic")
        
        if profiler: profiler.start_stage("tensor_updates")
        # Valid draft is all the draft tokens which are accepted by the main model
        valid_draft = draft_tokens[:, :accepted_tokens]

        # Concatenate the valid draft and correction token to get the new input ids
        new_tokens = torch.cat([valid_draft, correction_token], dim=1)

        # Never commit more than the requested number of tokens
        remaining_tokens = max_new_tokens - tokens_generated
        new_tokens = new_tokens[:, :remaining_tokens]

        input_ids = torch.cat([input_ids, new_tokens], dim=1)
        attention_mask = torch.ones_like(input_ids)
        if profiler: profiler.end_stage("tensor_updates")

        # Count actual output tokens, not the full speculative chunk
        tokens_this_step = new_tokens.shape[1]
        tokens_generated += tokens_this_step

        total_accepted_tokens += accepted_tokens
        draft_generated_tokens += actual_gamma
        total_steps += 1
        
        if tokens_generated >= max_new_tokens:
            step_ms = (time.time() - chunk_start) * 1000
            break
        
        # If the draft model is using cache, rollback the KV Cache to the actual valid length and speculate the next chunk
        generated = []
        if current_cache:
            if profiler: profiler.start_stage("draft_speculation")
            # Rollback target cache
            target_valid_len = input_len + accepted_tokens
            
            if accepted_tokens == actual_gamma:
                # last drafted token was accepted but its KV was never computed — backfill it
                last_draft_token = draft_tokens[:, -1:]
                backfill_mask = torch.ones((input_ids.shape[0], target_valid_len), device=device)
                backfill_pos = torch.tensor([[target_valid_len - 1]], device=device)
                outputs = draft_model(
                    last_draft_token,
                    attention_mask=backfill_mask,
                    position_ids=backfill_pos,
                    past_key_values=draft_cache,
                    use_cache=True,
                )
                draft_cache = outputs.past_key_values
            if profiler: profiler.end_stage("draft_speculation")
            
            if profiler: profiler.start_stage("cache_rollback")
            target_cache.crop(target_valid_len)
            draft_cache.crop(target_valid_len)
            if profiler: profiler.end_stage("cache_rollback")
            
            current_attention_mask = torch.ones((input_ids.shape[0], target_valid_len + 1), device=device)
            position_ids = torch.tensor([[target_valid_len]], device=device)
            
            outputs = draft_model(
                correction_token,
                attention_mask=current_attention_mask,
                position_ids=position_ids,
                past_key_values=draft_cache,
                use_cache=True
            )
            draft_cache = outputs.past_key_values
            
            current_input = torch.argmax(outputs.logits[:, -1:, :], dim=-1)
            generated.append(current_input)
            current_attention_mask = torch.ones(
                (input_ids.shape[0], target_valid_len+1),
                device=device
            )
            
            if profiler: profiler.start_stage("draft_speculation")
            for _ in range(current_gamma-1):
                current_attention_mask = torch.cat([
                    current_attention_mask,
                    torch.ones((input_ids.shape[0], 1), device=device)
                ], dim=1)
                position_ids = (current_attention_mask.cumsum(dim=-1) - 1)[:, -1:]
                
                outputs = draft_model(
                    current_input,
                    attention_mask=current_attention_mask,
                    position_ids=position_ids,
                    past_key_values=draft_cache,
                    use_cache=True
                )
                
                draft_cache = outputs.past_key_values
                logits = outputs.logits[:, -1, :]
                next_token = torch.argmax(logits, dim=-1, keepdim=True)
                
                generated.append(next_token)
                current_input = next_token
            if profiler: profiler.end_stage("draft_speculation")
            
            past_correction_token = correction_token
        else:
            if profiler: profiler.start_stage("draft_speculation")
            current_input = input_ids
            
            for _ in range(current_gamma):
                outputs = draft_model(
                    current_input,
                    use_cache=False
                )
                
                logits = outputs.logits[:, -1, :]
                next_token = torch.argmax(logits, dim=-1, keepdim=True)
                generated.append(next_token)
                
                current_input = torch.cat((current_input, next_token), dim=1)
            if profiler: profiler.end_stage("draft_speculation")
                
        # Generate the next speculated ids
        newly_generated_gamma = torch.cat(generated, dim=1)
        speculated_ids = torch.cat([input_ids, newly_generated_gamma], dim=1)

        step_ms = (time.time() - chunk_start) * 1000

        if controller is not None:
            steps += 1
            config_history.append((current_gamma, current_cache))
            tps_history.append(tokens_this_step / max(step_ms / 1000, 1e-9))

            # Ask controller for next config
            current_gamma, current_cache = controller.update(
                tokens_generated=tokens_this_step,
                step_time_ms=step_ms
            )

    # Acceptance rate is the total number of tokens accepted divided by total number of tokens generated by the draft model
    acceptance_rate = total_accepted_tokens / draft_generated_tokens
    # Mean accepted tokens is the average number of tokens accepted in each step
    mean_accepted = total_accepted_tokens / total_steps
    
    if profiler:
        breakdown, total_time = profiler.finalize()
        return input_ids, acceptance_rate, mean_accepted, breakdown, total_time

    if return_stats:
        if controller is not None:
            from collections import Counter
            total_tps = sum(tps_history) / len(tps_history) if tps_history else 0.0
            stats = {
                "mode": "Adaptive",
                "tokens_generated": tokens_generated,
                "steps": steps,
                "config_counts": dict(Counter(config_history)),
                "fallen_back": controller.fallen_back,
                "baseline_tps": controller.baseline_tps,
                "total_tps": total_tps,
                "final_gamma": current_gamma,
                "final_cache": current_cache,
                "acceptance_rate": acceptance_rate,
                "mean_accepted": mean_accepted
            }
        else:
            stats = {
                "mode": "Speculative",
                "acceptance_rate": acceptance_rate,
                "mean_accepted": mean_accepted
            }
        return input_ids, stats

    else:
        return input_ids
            
    
if __name__ == '__main__':
    # CLI Arguments
    parser = argparse.ArgumentParser("Speculative Inference Engine")
    
    parser.add_argument(
        "--main_model", type=str, default="main",
        choices=["main", "pythia-1B", "SmolLM-1.7B", "SmolLM2-1.7B"], help="Select main model for verification of draft tokens"
    )
    parser.add_argument(
        "--draft_model", type=str, default="draft_medium",
        choices=["draft_small", "draft_medium", "pythia-160M", "SmolLM-135M", "SmolLM2-135M"], help="Select draft model for speculative generation"
    )
    parser.add_argument(
        "--gamma", type=int, default=5, help="Number of draft tokens to speculate per step"
    )
    parser.add_argument(
        "--max_new_tokens", type=int, default=512, help="Maximum number of tokens to generate"
    )
    parser.add_argument(
        "--no_cache", action="store_true", help="Disable KV Cache"
    )
    parser.add_argument(
        "--return_stats", action="store_true", help="Return metrics"
    )
    parser.add_argument(
        "--adaptive", action="store_true", help="Use adaptive model"
    )
    args = parser.parse_args()
    
    main_model_name = args.main_model
    draft_model_name = args.draft_model
    gamma = args.gamma
    max_new_tokens = args.max_new_tokens
    use_cache = not args.no_cache
    return_stats = args.return_stats
    use_adaptive = args.adaptive

    # Load both models
    print(">> Loading Main Model...")
    main_model, main_tokenizer = get_model(model_name=main_model_name)
    print("\n>> Loading Draft Model...")
    draft_model, draft_tokenizer = get_model(model_name=draft_model_name)

    if main_model and draft_model:
        main_model.generation_config.pad_token_id = main_tokenizer.pad_token_id
        draft_model.generation_config.pad_token_id = draft_tokenizer.pad_token_id

        # Put both models in eval model
        main_model.eval()
        draft_model.eval()
        
        # Take the prompt as input and tokenize it
        prompt = input("\nPlease enter the prompt: ")


        inputs = main_tokenizer(prompt, return_tensors="pt")
        input_ids = inputs.input_ids.to(DEVICE)
        attention_mask = inputs.attention_mask.to(DEVICE)

        if use_adaptive:
            init_start = time.time()
            print(f">> [speculative_engine] Using adaptive controller\n")
            controller = AdaptiveController(
                alpha=0.2,
                eval_every=10,
                re_explore_every=None
            )

            sd_viable = controller.initialize(
                main_model=main_model,
                draft_model=draft_model,
                input_ids=input_ids,
                attention_mask=attention_mask,
                device=DEVICE,
                use_cache=use_cache
            )
            init_time = time.time() - init_start
        else:
            print(f">> [speculative_engine] Using vanilla speculative decoding\n")
            controller = None
            sd_viable = True

        gen_start = time.time()
        if not sd_viable:
            print("[speculative_engine] SD not viable -> Using AR Baseline]")
            output_ids = generate(
                main_model,
                input_ids=input_ids,
                attention_mask=attention_mask,
                tokenizer=main_tokenizer,
                max_new_tokens=max_new_tokens,
                use_cache=use_cache
            )

            if return_stats:
                stats = {"mode": "Autoregressive", "reason": "ratio < 1.0"}

        else:
            if return_stats:
                if main_model_name == 'main' and draft_model_name in ['draft_small', 'draft_medium']:
                    output_ids, stats = generate_speculative_custom(main_model, draft_model, input_ids, max_new_tokens=max_new_tokens, gamma=gamma, use_cache=use_cache, return_stats=return_stats)
                else:
                    output_ids, stats = generate_speculative_standard(main_model, draft_model, input_ids, attention_mask, max_new_tokens=max_new_tokens, gamma=gamma, use_cache=use_cache, return_stats=return_stats, controller=controller)

            else:
                if main_model_name == 'main' and draft_model_name in ['draft_small', 'draft_medium']:
                    output_ids = generate_speculative_custom(main_model, draft_model, input_ids, max_new_tokens=max_new_tokens, gamma=gamma, use_cache=use_cache, return_stats=return_stats)
                else:
                    output_ids = generate_speculative_standard(main_model, draft_model, input_ids, attention_mask, max_new_tokens=max_new_tokens, gamma=gamma, use_cache=use_cache, return_stats=return_stats, controller=controller)

        gen_time = time.time() - gen_start

        text = main_tokenizer.decode(output_ids[0].tolist(), skip_special_tokens=True)
        print(f"\n>> Output: {text}")

        if return_stats:
            print(f">> Stats: {stats}")

        print(f"\n>> Generation Time : {gen_time}")
        if controller:
            print(f">> Controller Initialization Time : {init_time}")